-- ═══════════════════════════════════════════════════════════════════
-- JoyJump v4 — Database Schema
-- Run this in: Supabase → SQL Editor → New query → Run
--
-- SAFE TO RUN IN ONE SHOT — no auth dependency required.
-- Works in demo mode (no login) and production mode (with Auth).
-- ═══════════════════════════════════════════════════════════════════

-- ── Extensions ──────────────────────────────────────────────────
create extension if not exists "uuid-ossp";

-- ── Children ────────────────────────────────────────────────────
-- Each child gets a UUID generated by the browser (store.childId).
-- parent_auth_id is null in demo mode; set to auth.uid() when
-- Supabase Auth is enabled in Phase 1b.
create table if not exists children (
  id              uuid primary key default uuid_generate_v4(),
  parent_auth_id  uuid,                    -- null until Phase 1b Auth
  name            text not null default 'Learner',
  grade           integer default 3,
  avatar          text default 'panda',
  stars           integer default 0,
  coins           integer default 0,
  streak          integer default 0,
  last_play_date  date,
  unlocked_worlds text[] default array['math'],
  created_at      timestamptz default now()
);

-- ── Progress (best score per lesson per child) ──────────────────
create table if not exists progress (
  id          uuid primary key default uuid_generate_v4(),
  child_id    uuid not null,
  lesson_id   text not null,
  best_score  integer default 0 check (best_score between 0 and 3),
  completed   boolean default false,
  attempts    integer default 0,
  first_at    timestamptz default now(),
  last_at     timestamptz default now(),
  unique(child_id, lesson_id)
);

-- ── Attempt logs (full history — never updated, only inserted) ──
create table if not exists attempt_logs (
  id          uuid primary key default uuid_generate_v4(),
  child_id    uuid not null,
  lesson_id   text not null,
  score       integer check (score between 0 and 3),
  time_spent  integer default 0,
  phase_data  jsonb,
  played_at   timestamptz default now()
);

-- ── Session logs (time-on-task) ─────────────────────────────────
create table if not exists session_logs (
  id           uuid primary key default uuid_generate_v4(),
  child_id     uuid not null,
  started_at   timestamptz not null default now(),
  ended_at     timestamptz,
  duration_sec integer,
  lessons_done integer default 0,
  date         date default current_date
);

-- ── Badges ──────────────────────────────────────────────────────
create table if not exists badges (
  id         uuid primary key default uuid_generate_v4(),
  child_id   uuid not null,
  badge_id   text not null,
  earned_at  timestamptz default now(),
  unique(child_id, badge_id)
);

-- ── Web Vitals (performance monitoring) ────────────────────────
create table if not exists web_vitals (
  id           uuid primary key default uuid_generate_v4(),
  metric_name  text not null,
  value        integer not null,
  rating       text,
  metric_id    text,
  page         text,
  user_agent   text,
  recorded_at  timestamptz default now()
);

-- ── Indexes ─────────────────────────────────────────────────────
create index if not exists idx_progress_child     on progress(child_id);
create index if not exists idx_progress_lesson    on progress(lesson_id);
create index if not exists idx_attempts_child     on attempt_logs(child_id);
create index if not exists idx_attempts_lesson    on attempt_logs(lesson_id);
create index if not exists idx_attempts_date      on attempt_logs(played_at);
create index if not exists idx_sessions_child     on session_logs(child_id);
create index if not exists idx_sessions_date      on session_logs(date);
create index if not exists idx_vitals_name        on web_vitals(metric_name);
create index if not exists idx_vitals_date        on web_vitals(recorded_at);

-- ── Row Level Security ──────────────────────────────────────────
-- Demo mode: all tables are open for insert/select by the app.
-- This lets JoyJump work without any login.
--
-- Phase 1b upgrade path: replace these with auth-scoped policies
-- once Supabase Auth (magic link) is enabled.
alter table children     enable row level security;
alter table progress     enable row level security;
alter table attempt_logs enable row level security;
alter table session_logs enable row level security;
alter table badges       enable row level security;
alter table web_vitals   enable row level security;

-- Children: app can read/write (keyed by UUID from localStorage)
create policy "children_open"
  on children for all
  using (true)
  with check (true);

-- Progress: open read/write
create policy "progress_open"
  on progress for all
  using (true)
  with check (true);

-- Attempt logs: insert only (no reads needed from client)
create policy "attempts_insert"
  on attempt_logs for insert
  with check (true);

create policy "attempts_read"
  on attempt_logs for select
  using (true);

-- Session logs: insert + read
create policy "sessions_insert"
  on session_logs for insert
  with check (true);

create policy "sessions_read"
  on session_logs for select
  using (true);

-- Badges: open read/write
create policy "badges_open"
  on badges for all
  using (true)
  with check (true);

-- Web vitals: insert only from browser
create policy "vitals_insert"
  on web_vitals for insert
  with check (true);

-- ── upsert_progress RPC ─────────────────────────────────────────
-- Called from lib/progress.js on lesson completion.
-- Best score wins + logs every attempt separately.
create or replace function upsert_progress(
  p_child_id  uuid,
  p_lesson_id text,
  p_score     integer,
  p_time_sec  integer  default 0,
  p_phase     jsonb    default null
) returns void
language plpgsql
security definer
as $$
begin
  -- Upsert best score row
  insert into progress
    (child_id, lesson_id, best_score, completed, attempts, first_at, last_at)
  values
    (p_child_id, p_lesson_id, p_score, true, 1, now(), now())
  on conflict (child_id, lesson_id) do update set
    best_score = greatest(progress.best_score, excluded.best_score),
    completed  = true,
    attempts   = progress.attempts + 1,
    last_at    = now();

  -- Always insert a fresh attempt record
  insert into attempt_logs
    (child_id, lesson_id, score, time_spent, phase_data)
  values
    (p_child_id, p_lesson_id, p_score, p_time_sec, p_phase);
end;
$$;

-- ═══════════════════════════════════════════════════════════════════
-- PHASE 1b UPGRADE (run this AFTER enabling Supabase Auth)
-- ═══════════════════════════════════════════════════════════════════
-- When you add magic-link login in Phase 1b, run these statements
-- to tighten security. DO NOT run now — auth.users won't exist yet.
--
-- 1. Create parent_profiles table linked to auth.users:
--
--   create table parent_profiles (
--     id         uuid primary key references auth.users(id) on delete cascade,
--     name       text,
--     email      text,
--     created_at timestamptz default now()
--   );
--
--   create or replace function handle_new_user()
--   returns trigger language plpgsql security definer as $$
--   begin
--     insert into parent_profiles (id, email)
--     values (new.id, new.email)
--     on conflict do nothing;
--     return new;
--   end;
--   $$;
--
--   create trigger on_auth_user_created
--     after insert on auth.users
--     for each row execute procedure handle_new_user();
--
-- 2. Add parent_auth_id FK on children:
--
--   alter table children
--     add constraint children_parent_fk
--     foreign key (parent_auth_id) references auth.users(id);
--
-- 3. Replace open RLS policies with scoped ones:
--
--   drop policy "children_open" on children;
--   create policy "children_scoped" on children for all
--     using (parent_auth_id = auth.uid())
--     with check (parent_auth_id = auth.uid());
--
--   drop policy "progress_open" on progress;
--   create policy "progress_scoped" on progress for all
--     using (
--       child_id in (
--         select id from children where parent_auth_id = auth.uid()
--       )
--     );
--   -- (repeat pattern for attempt_logs, session_logs, badges)
-- ═══════════════════════════════════════════════════════════════════
